export const ROUTES = {
  root: '/',
  pay: '/pay',
  productsAll: '/products',
  productsType: '/products/type',
  productID: '/product/id',
  auth: '/auth',
  authFormik: '/authFormik',
  register: '/register',
  basket: '/basket',
  plug: '/plug',
  delivery: '/delivery',
  search: '/search',
  // order: '/order',
  // addProduct: '/addProduct',
  // personalData: '/personalData',
  // editOrder: '/editOrder',
  // orderID: '/id',
  
  // личный кабинет:
  cabinet: '/cabinet',
  order: '/cabinet/order',
  mybasket: '/cabinet/basket',
  personalData: '/cabinet/personalData',
 
  // админка:
  admin: '/admin',
  addProduct: '/admin/addProduct',
  // addProduct: 'addProduct',
  // deleteProduct: '/admin/deleteProduct',
  editProduct: '/admin/editProduct',
  addUser: '/admin/addUser',
  editUser: '/admin/editUser',
  editOrder: '/admin/editOrder',
  orderID: '/admin/editOrder/id',
};
